# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='weight',
            field=models.IntegerField(verbose_name='WEIGHT'),
        ),
    ]
